### ISSUE TITLE
Bitbucket.pipelines.getStepLog response Body is Bitbucket.Schema.Error

### ISSUE THREAD

**Issue by ejlax** [MunifTanjim/node-bitbucket#20] opened 2019-02-28 14:45 UTC
I was looking to implement the use of step logs in our cli tool, it appears that the `getStepLog` only returns the `Bitbucket.Schema.Error` interface.

    getStepLog(params: Bitbucket.Params.PipelinesGetStepLog, callback?: Bitbucket.Callback<Bitbucket.Response<Bitbucket.Schema.Error>>): Promise<Bitbucket.Response<Bitbucket.Schema.Error>>;

Is this an oversight or a placeholder for future implementation?

**Comment by MunifTanjim** [comment] 2019-02-28 16:55
@ejlax Thanks for reporting this.

This should be fixed on v[`1.9.0`](https://www.npmjs.com/package/bitbucket/v/1.9.0) :tada: 

> Is this an oversight or a placeholder for future implementation?

This was caused by a tiny mistake in the routes generation script.

**Closed** 2019-03-06 08:28 UTC
